# Generated by Django 6.0.6 on 2026-06-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppoll',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouppoll',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='grouppoll',
            name='message_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('session', 'question', 'user'), name='unique_user_answer_per_session_question'),
        ),
        migrations.AddConstraint(
            model_name='grouppoll',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_poll_per_session_question'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_option_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_correct_option_per_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('subtest', 'order'), name='unique_question_order_per_subtest'),
        ),
        migrations.AddConstraint(
            model_name='quizsession',
            constraint=models.CheckConstraint(condition=models.Q(('current_index__lte', models.F('total'))), name='session_index_not_above_total'),
        ),
        migrations.AddConstraint(
            model_name='quizsession',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', models.F('total'))), name='session_score_not_above_total'),
        ),
        migrations.AddConstraint(
            model_name='quizsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chat_id__isnull', False), ('mode', 'group')), models.Q(('chat_id__isnull', True), ('mode', 'solo')), _connector='OR'), name='session_mode_chat_consistent'),
        ),
    ]
