# Generated by Django 6.0.6 on 2026-06-08 13:09

from django.db import migrations, models


def populate_question_ids(apps, schema_editor):
    QuizSession = apps.get_model("quiz", "QuizSession")
    Question = apps.get_model("quiz", "Question")
    for session in QuizSession.objects.all().iterator():
        question_ids = list(
            Question.objects.filter(subtest_id=session.subtest_id)
            .order_by("order", "id")
            .values_list("id", flat=True)[:session.total]
        )
        QuizSession.objects.filter(id=session.id).update(
            question_ids=question_ids
        )


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_grouppoll_closed_at_grouppoll_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(
            populate_question_ids,
            migrations.RunPython.noop,
        ),
    ]
