# Generated by Django 6.0.6 on 2026-06-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_testgroup'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'mode', '-started_at'], name='session_user_mode_started'),
        ),
    ]
