# Generated by Django 5.2.15 on 2026-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizsession_session_user_mode_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='time_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Savolga vaqt (soniya)'),
        ),
        migrations.AddField(
            model_name='testgroup',
            name='timer_allow_none',
            field=models.BooleanField(default=False, verbose_name="'Vaqt yo'q' varianti"),
        ),
        migrations.AddField(
            model_name='testgroup',
            name='timer_enabled',
            field=models.BooleanField(default=False, verbose_name='Vaqt sozlamasi yoqilgan'),
        ),
        migrations.AddField(
            model_name='testgroup',
            name='timer_options',
            field=models.JSONField(blank=True, default=list, verbose_name='Vaqt variantlari (soniya)'),
        ),
    ]
